const countryCodeData = {
    "AFG": { name: "Afghanistan", alpha2: "af" },
    "ALB": { name: "Albania", alpha2: "al" },
    "DZA": { name: "Algeria", alpha2: "dz" },
    "ASM": { name: "American Samoa", alpha2: "as" },
    "AND": { name: "Andorra", alpha2: "ad" },
    "AGO": { name: "Angola", alpha2: "ao" },
    "AIA": { name: "Anguilla", alpha2: "ai" },
    "ATA": { name: "Antarctica", alpha2: "aq" },
    "ATG": { name: "Antigua and Barbuda", alpha2: "ag" },
    "ARG": { name: "Argentina", alpha2: "ar" },
    "ARM": { name: "Armenia", alpha2: "am" },
    "ABW": { name: "Aruba", alpha2: "aw" },
    "AUS": { name: "Australia", alpha2: "au" },
    "AUT": { name: "Austria", alpha2: "at" },
    "AZE": { name: "Azerbaijan", alpha2: "az" },
    "BHS": { name: "Bahamas", alpha2: "bs" },
    "BHR": { name: "Bahrain", alpha2: "bh" },
    "BGD": { name: "Bangladesh", alpha2: "bd" },
    "BRB": { name: "Barbados", alpha2: "bb" },
    "BLR": { name: "Belarus", alpha2: "by" },
    "BEL": { name: "Belgium", alpha2: "be" },
    "BLZ": { name: "Belize", alpha2: "bz" },
    "BEN": { name: "Benin", alpha2: "bj" },
    "BMU": { name: "Bermuda", alpha2: "bm" },
    "BTN": { name: "Bhutan", alpha2: "bt" },
    "BOL": { name: "Bolivia", alpha2: "bo" },
    "BES": { name: "Bonaire, Sint Eustatius and Saba", alpha2: "bq" },
    "BIH": { name: "Bosnia and Herz.", alpha2: "ba" },
    "BWA": { name: "Botswana", alpha2: "bw" },
    "BVT": { name: "Bouvet Island", alpha2: "bv" },
    "BRA": { name: "Brazil", alpha2: "br" },
    "IOT": { name: "British Indian Ocean Territory (the)", alpha2: "io" },
    "BRN": { name: "Brunei Darussalam", alpha2: "bn" },
    "BGR": { name: "Bulgaria", alpha2: "bg" },
    "BFA": { name: "Burkina Faso", alpha2: "bf" },
    "BDI": { name: "Burundi", alpha2: "bi" },
    "CPV": { name: "Cabo Verde", alpha2: "cv" },
    "KHM": { name: "Cambodia", alpha2: "kh" },
    "CMR": { name: "Cameroon", alpha2: "cm" },
    "CAN": { name: "Canada", alpha2: "ca" },
    "CYM": { name: "Cayman Islands (the)", alpha2: "ky" },
    "CAF": { name: "Central African Republic (the)", alpha2: "cf" },
    "TCD": { name: "Chad", alpha2: "td" },
    "CHL": { name: "Chile", alpha2: "cl" },
    "CHN": { name: "China", alpha2: "cn" },
    "CXR": { name: "Christmas Island", alpha2: "cx" },
    "CCK": { name: "Cocos (Keeling) Islands (the)", alpha2: "cc" },
    "COL": { name: "Colombia", alpha2: "co" },
    "COM": { name: "Comoros (the)", alpha2: "km" },
    "COD": { name: "Congo (the Democratic Republic of the)", alpha2: "cd" },
    "COG": { name: "Congo (the)", alpha2: "cg" },
    "COK": { name: "Cook Islands (the)", alpha2: "ck" },
    "CRI": { name: "Costa Rica", alpha2: "cr" },
    "HRV": { name: "Croatia", alpha2: "hr" },
    "CUB": { name: "Cuba", alpha2: "cu" },
    "CUW": { name: "Cura?ao", alpha2: "cw" },
    "CYP": { name: "Cyprus", alpha2: "cy" },
    "CZE": { name: "Czech Rep.", alpha2: "cz" },
    "CIV": { name: "C?te d'Ivoire", alpha2: "ci" },
    "DNK": { name: "Denmark", alpha2: "dk" },
    "DJI": { name: "Djibouti", alpha2: "dj" },
    "DMA": { name: "Dominica", alpha2: "dm" },
    "DOM": { name: "Dominican Rep.", alpha2: "do" },
    "ECU": { name: "Ecuador", alpha2: "ec" },
    "EGY": { name: "Egypt", alpha2: "eg" },
    "SLV": { name: "El Salvador", alpha2: "sv" },
    "GNQ": { name: "Equatorial Guinea", alpha2: "gq" },
    "ERI": { name: "Eritrea", alpha2: "er" },
    "EST": { name: "Estonia", alpha2: "ee" },
    "SWZ": { name: "Eswatini", alpha2: "sz" },
    "ETH": { name: "Ethiopia", alpha2: "et" },
    "FLK": { name: "Falkland Islands (the) [Malvinas]", alpha2: "fk" },
    "FRO": { name: "Faroe Islands (the)", alpha2: "fo" },
    "FJI": { name: "Fiji", alpha2: "fj" },
    "FIN": { name: "Finland", alpha2: "fi" },
    "FRA": { name: "France", alpha2: "fr" },
    "GUF": { name: "French Guiana", alpha2: "gf" },
    "PYF": { name: "French Polynesia", alpha2: "pf" },
    "ATF": { name: "French Southern Territories (the)", alpha2: "tf" },
    "GAB": { name: "Gabon", alpha2: "ga" },
    "GMB": { name: "Gambia (the)", alpha2: "gm" },
    "GEO": { name: "Georgia", alpha2: "ge" },
    "DEU": { name: "Germany", alpha2: "de" },
    "GHA": { name: "Ghana", alpha2: "gh" },
    "GIB": { name: "Gibraltar", alpha2: "gi" },
    "GRC": { name: "Greece", alpha2: "gr" },
    "GRL": { name: "Greenland", alpha2: "gl" },
    "GRD": { name: "Grenada", alpha2: "gd" },
    "GLP": { name: "Guadeloupe", alpha2: "gp" },
    "GUM": { name: "Guam", alpha2: "gu" },
    "GTM": { name: "Guatemala", alpha2: "gt" },
    "GGY": { name: "Guernsey", alpha2: "gg" },
    "GIN": { name: "Guinea", alpha2: "gn" },
    "GNB": { name: "Guinea-Bissau", alpha2: "gw" },
    "GUY": { name: "Guyana", alpha2: "gy" },
    "HTI": { name: "Haiti", alpha2: "ht" },
    "HMD": { name: "Heard Island and McDonald Islands", alpha2: "hm" },
    "VAT": { name: "Holy See (the)", alpha2: "va" },
    "HND": { name: "Honduras", alpha2: "hn" },
    "HKG": { name: "Hong Kong", alpha2: "hk" },
    "HUN": { name: "Hungary", alpha2: "hu" },
    "ISL": { name: "Iceland", alpha2: "is" },
    "IND": { name: "India", alpha2: "in" },
    "IDN": { name: "Indonesia", alpha2: "id" },
    "IRN": { name: "Iran", alpha2: "ir" },
    "IRQ": { name: "Iraq", alpha2: "iq" },
    "IRL": { name: "Ireland", alpha2: "ie" },
    "IMN": { name: "Isle of Man", alpha2: "im" },
    "ISR": { name: "Israel", alpha2: "il" },
    "ITA": { name: "Italy", alpha2: "it" },
    "JAM": { name: "Jamaica", alpha2: "jm" },
    "JPN": { name: "Japan", alpha2: "jp" },
    "JEY": { name: "Jersey", alpha2: "je" },
    "JOR": { name: "Jordan", alpha2: "jo" },
    "KAZ": { name: "Kazakhstan", alpha2: "kz" },
    "KEN": { name: "Kenya", alpha2: "ke" },
    "KIR": { name: "Kiribati", alpha2: "ki" },
    "PRK": { name: "Dem. Rep. Korea", alpha2: "kp" },
    "KOR": { name: "Korea", alpha2: "kr" },
    "KWT": { name: "Kuwait", alpha2: "kw" },
    "KGZ": { name: "Kyrgyzstan", alpha2: "kg" },
    "LAO": { name: "Lao PDR", alpha2: "la" },
    "LVA": { name: "Latvia", alpha2: "lv" },
    "LBN": { name: "Lebanon", alpha2: "lb" },
    "LSO": { name: "Lesotho", alpha2: "ls" },
    "LBR": { name: "Liberia", alpha2: "lr" },
    "LBY": { name: "Libya", alpha2: "ly" },
    "LIE": { name: "Liechtenstein", alpha2: "li" },
    "LTU": { name: "Lithuania", alpha2: "lt" },
    "LUX": { name: "Luxembourg", alpha2: "lu" },
    "MAC": { name: "Macao", alpha2: "mo" },
    "MDG": { name: "Madagascar", alpha2: "mg" },
    "MWI": { name: "Malawi", alpha2: "mw" },
    "MYS": { name: "Malaysia", alpha2: "my" },
    "MDV": { name: "Maldives", alpha2: "mv" },
    "MLI": { name: "Mali", alpha2: "ml" },
    "MLT": { name: "Malta", alpha2: "mt" },
    "MHL": { name: "Marshall Islands (the)", alpha2: "mh" },
    "MTQ": { name: "Martinique", alpha2: "mq" },
    "MRT": { name: "Mauritania", alpha2: "mr" },
    "MUS": { name: "Mauritius", alpha2: "mu" },
    "MYT": { name: "Mayotte", alpha2: "yt" },
    "MEX": { name: "Mexico", alpha2: "mx" },
    "FSM": { name: "Micronesia", alpha2: "fm" },
    "MDA": { name: "Moldova", alpha2: "md" },
    "MCO": { name: "Monaco", alpha2: "mc" },
    "MNG": { name: "Mongolia", alpha2: "mn" },
    "MNE": { name: "Montenegro", alpha2: "me" },
    "MSR": { name: "Montserrat", alpha2: "ms" },
    "MAR": { name: "Morocco", alpha2: "ma" },
    "MOZ": { name: "Mozambique", alpha2: "mz" },
    "MMR": { name: "Myanmar", alpha2: "mm" },
    "NRU": { name: "Nauru", alpha2: "nr" },
    "NPL": { name: "Nepal", alpha2: "np" },
    "NLD": { name: "Netherlands", alpha2: "nl" },
    "NCL": { name: "New Caledonia", alpha2: "nc" },
    "NZL": { name: "New Zealand", alpha2: "nz" },
    "NIC": { name: "Nicaragua", alpha2: "ni" },
    "NER": { name: "Niger (the)", alpha2: "ne" },
    "NGA": { name: "Nigeria", alpha2: "ng" },
    "NIU": { name: "Niue", alpha2: "nu" },
    "NFK": { name: "Norfolk Island", alpha2: "nf" },
    "MNP": { name: "Northern Mariana Islands (the)", alpha2: "mp" },
    "NOR": { name: "Norway", alpha2: "no" },
    "OMN": { name: "Oman", alpha2: "om" },
    "PAK": { name: "Pakistan", alpha2: "pk" },
    "PLW": { name: "Palau", alpha2: "pw" },
    "PSE": { name: "Palestine, State of", alpha2: "ps" },
    "PAN": { name: "Panama", alpha2: "pa" },
    "PNG": { name: "Papua New Guinea", alpha2: "pg" },
    "PRY": { name: "Paraguay", alpha2: "py" },
    "PER": { name: "Peru", alpha2: "pe" },
    "PHL": { name: "Philippines", alpha2: "ph" },
    "PCN": { name: "Pitcairn", alpha2: "pn" },
    "POL": { name: "Poland", alpha2: "pl" },
    "PRT": { name: "Portugal", alpha2: "pt" },
    "PRI": { name: "Puerto Rico", alpha2: "pr" },
    "QAT": { name: "Qatar", alpha2: "qa" },
    "MKD": { name: "Macedonia", alpha2: "mk" },
    "ROU": { name: "Romania", alpha2: "ro" },
    "RUS": { name: "Russia", alpha2: "ru" },
    "RWA": { name: "Rwanda", alpha2: "rw" },
    "REU": { name: "R?union", alpha2: "re" },
    "BLM": { name: "Saint Barth?lemy", alpha2: "bl" },
    "SHN": { name: "Saint Helena, Ascension and Tristan da Cunha", alpha2: "sh" },
    "KNA": { name: "Saint Kitts and Nevis", alpha2: "kn" },
    "LCA": { name: "Saint Lucia", alpha2: "lc" },
    "MAF": { name: "Saint Martin (French part)", alpha2: "mf" },
    "SPM": { name: "Saint Pierre and Miquelon", alpha2: "pm" },
    "VCT": { name: "Saint Vincent and the Grenadines", alpha2: "vc" },
    "WSM": { name: "Samoa", alpha2: "ws" },
    "SMR": { name: "San Marino", alpha2: "sm" },
    "STP": { name: "Sao Tome and Principe", alpha2: "st" },
    "SAU": { name: "Saudi Arabia", alpha2: "sa" },
    "SEN": { name: "Senegal", alpha2: "sn" },
    "SRB": { name: "Serbia", alpha2: "rs" },
    "SYC": { name: "Seychelles", alpha2: "sc" },
    "SLE": { name: "Sierra Leone", alpha2: "sl" },
    "SGP": { name: "Singapore", alpha2: "sg" },
    "SXM": { name: "Sint Maarten (Dutch part)", alpha2: "sx" },
    "SVK": { name: "Slovakia", alpha2: "sk" },
    "SVN": { name: "Slovenia", alpha2: "si" },
    "SLB": { name: "Solomon Is.", alpha2: "sb" },
    "SOM": { name: "Somalia", alpha2: "so" },
    "ZAF": { name: "South Africa", alpha2: "za" },
    "SGS": { name: "South Georgia and the South Sandwich Islands", alpha2: "gs" },
    "SSD": { name: "S. Sudan", alpha2: "ss" },
    "ESP": { name: "Spain", alpha2: "es" },
    "LKA": { name: "Sri Lanka", alpha2: "lk" },
    "SDN": { name: "Sudan", alpha2: "sd" },
    "SUR": { name: "Suriname", alpha2: "sr" },
    "SJM": { name: "Svalbard and Jan Mayen", alpha2: "sj" },
    "SWE": { name: "Sweden", alpha2: "se" },
    "CHE": { name: "Switzerland", alpha2: "ch" },
    "SYR": { name: "Syria", alpha2: "sy" },
    "TWN": { name: "Taiwan (Province of China)", alpha2: "tw" },
    "TJK": { name: "Tajikistan", alpha2: "tj" },
    "TZA": { name: "Tanzania, United Republic of", alpha2: "tz" },
    "THA": { name: "Thailand", alpha2: "th" },
    "TLS": { name: "Timor-Leste", alpha2: "tl" },
    "TGO": { name: "Togo", alpha2: "tg" },
    "TKL": { name: "Tokelau", alpha2: "tk" },
    "TON": { name: "Tonga", alpha2: "to" },
    "TTO": { name: "Trinidad and Tobago", alpha2: "tt" },
    "TUN": { name: "Tunisia", alpha2: "tn" },
    "TUR": { name: "Turkey", alpha2: "tr" },
    "TKM": { name: "Turkmenistan", alpha2: "tm" },
    "TCA": { name: "Turks and Caicos Islands (the)", alpha2: "tc" },
    "TUV": { name: "Tuvalu", alpha2: "tv" },
    "UGA": { name: "Uganda", alpha2: "ug" },
    "UKR": { name: "Ukraine", alpha2: "ua" },
    "ARE": { name: "United Arab Emirates (the)", alpha2: "ae" },
    "GBR": { name: "United Kingdom", alpha2: "gb" },
    "UMI": { name: "United States Minor Outlying Islands (the)", alpha2: "um" },
    "USA": { name: "United States", alpha2: "us" },
    "URY": { name: "Uruguay", alpha2: "uy" },
    "UZB": { name: "Uzbekistan", alpha2: "uz" },
    "VUT": { name: "Vanuatu", alpha2: "vu" },
    "VEN": { name: "Venezuela", alpha2: "ve" },
    "VNM": { name: "Vietnam", alpha2: "vn" },
    "VGB": { name: "Virgin Islands (British)", alpha2: "vg" },
    "VIR": { name: "Virgin Islands (U.S.)", alpha2: "vi" },
    "WLF": { name: "Wallis and Futuna", alpha2: "wf" },
    "ESH": { name: "Western Sahara", alpha2: "eh" },
    "YEM": { name: "Yemen", alpha2: "ye" },
    "ZMB": { name: "Zambia", alpha2: "zm" },
    "ZWE": { name: "Zimbabwe", alpha2: "zw" },
    "ALA": { name: "?land Islands", alpha2: "ax" }
};

const nameToCode = {};
for (const code in countryCodeData) {
    nameToCode[countryCodeData[code].name] = code;
}